//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.5

pub mod prelude;

pub mod answers;
pub mod comments;
pub mod question_tags;
pub mod questions;
pub mod tags;
pub mod users;
pub mod votes;

// Re-export commonly used types
pub use users::{Entity as Users, Model as UserModel, ActiveModel as UserActiveModel};
pub use answers::{Entity as Answers, Model as AnswerModel};
pub use comments::{Entity as Comments, Model as CommentModel};
pub use questions::{Entity as Questions, Model as QuestionModel};
pub use votes::{Entity as Votes, Model as VoteModel};
